version: 1

builds:
  - name: your-project-name
    env:
      - CGO_ENABLED=0
    goos: [ linux, windows, darwin ]
    goarch: [ amd64, arm64 ]
    goarm: [ 7 ]
    flags: [ -trimpath ]
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}

archives:
  - format: tar.gz
    files: [ LICENSE*, README* ]
    name_template: >-
      {{ .ProjectName }}_
      {{ .Version }}_
      {{ .Os }}_
      {{ .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
  - format: zip
    files: [ LICENSE*, README* ]
    name_template: >-
      {{ .ProjectName }}_
      {{ .Version }}_
      {{ .Os }}_
      {{ .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

release:
  github:
    owner: your-github-username
    repo: your-repo-name
  allow-update: true
  draft: false
  prerelease: false
  auto: true

changelog:
  disable: "{{ .Env.CREATE_CHANGELOG }}"
  sort: asc
  filters:
    exclude: [ "^docs:", "^test:" ]

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

metadata:
  homepage: "https://github.com/your-github-username/your-repo-name"
  description: "Your project description"
  license: "MIT"