version: 1

builds:
  - env:  
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - 7
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}

archives:
  - format: tar.gz
    files:
      - LICENSE*
      - README*
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  - format: zip
    files:
      - LICENSE*
      - README*
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

release:
  github:
    owner: fofcn 
  draft: false
  prerelease: false
  # 移除不支持的 allow_update 和 auto 字段

# 按需启用（若需禁用 Changelog，取消注释并确保 CREATE_CHANGELOG 环境变量为 true）
# changelog:
#   disable: "{{ .Env.CREATE_CHANGELOG }}"
#   sort: asc
#   filters:
#     exclude:
#       - "^docs:"
#       - "^test:"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

# 完全删除不支持的 metadata 节点